### ISSUE TITLE
Getting fault in smartpca

### ISSUE THREAD

**Issue by aman71197** [DReichLab/EIG#18]
I am running smartPCA with fastmode: YES on a dataset of 188380 SNPs and 50k individuals.
After running like for 200 mins it gives the following error.

`Illegal instruction     (core dumped) smartpca -p par.data > data.log`

**Comment by bumblenick** [comment]
Sorry about this but not much I can do from this info.  You either have to send me your data or run
a debugger like GDP

Nick

**Comment by aman71197** [comment]
The dataset is like 10GB. The output of gdb is : 

`(gdb) core core.19167 
[New Thread 19167]
[New Thread 19178]
[New Thread 19168]
[New Thread 19177]
[New Thread 19176]
[New Thread 19169]
[New Thread 19172]
[New Thread 19175]
[New Thread 19173]
[New Thread 19170]
[New Thread 19174]
[New Thread 19171]
Missing separate debuginfo for /u/home/a/aman7119/lib/openblas/lib/libopenblas.so.0
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/de/909f9afe3ff982900147b2b44ba1e3d47eb2e0
Missing separate debuginfo for 
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/8a/e3a3f6c1ee11993e86943052401329c9c5119a
Reading symbols from /usr/lib64/libgsl.so.0...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libgsl.so.0
Reading symbols from /u/home/a/aman7119/lib/openblas/lib/libopenblas.so.0...(no debugging symbols found)...done.
Loaded symbols for /u/home/a/aman7119/lib/openblas/lib/libopenblas.so.0
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /usr/lib64/libgfortran.so.3...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libgfortran.so.3
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Core was generated by `smartpca -p par.not_missing'.
Program terminated with signal 4, Illegal instruction.
#0  0x00002ace3f0d862c in dgemm_kernel () from /u/home/a/aman7119/lib/openblas/lib/libopenblas.so.0
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.192.el6.x86_64 gsl-1.13-1.el6.x86_64 libgfortran-4.4.7-17.el6.x86_64
(gdb) bt
#0  0x00002ace3f0d862c in dgemm_kernel () from /u/home/a/aman7119/lib/openblas/lib/libopenblas.so.0
#1  0x000000000000000c in ?? ()
#2  0x000000000000000c in ?? ()
#3  0x00002aceee06c000 in ?? ()
#4  0x0000000000000100 in ?? ()
#5  0x000000000000000c in ?? ()
#6  0x000000000000c350 in ?? ()
#7  0x00002ace3e7e79d5 in _dl_runtime_resolve () from /lib64/ld-linux-x86-64.so.2
#8  0x00002ace3ef56cf7 in dgemm_nn () from /u/home/a/aman7119/lib/openblas/lib/libopenblas.so.0
#9  0x00002ace3ef6c678 in dgemm_thread_nn () from /u/home/a/aman7119/lib/openblas/lib/libopenblas.so.0
#10 0x00002ace3ee86e9a in cblas_dgemm () from /u/home/a/aman7119/lib/openblas/lib/libopenblas.so.0
#11 0x00002ace3ea4922d in gsl_blas_dgemm () from /usr/lib64/libgsl.so.0
#12 0x000000000044b076 in kjg_fpca_XTXA ()
#13 0x000000000044ab68 in kjg_fpca ()
#14 0x0000000000403d6f in main ()
`
